environment=staging
applicationId=com.rola.app.staging
firebaseProjectId=rola-staging
apiBaseUrl=https://us-central1-rola-staging.cloudfunctions.net/api/
releaseTrack=closed
analyticsCollection=true
crashlyticsCollection=true
modelChannel=staging
