environment=production
applicationId=com.rola.app
firebaseProjectId=rola-production
apiBaseUrl=https://us-central1-rola-production.cloudfunctions.net/api/
releaseTrack=production
analyticsCollection=true
crashlyticsCollection=true
modelChannel=production
