environment=dev
applicationId=com.rola.app.dev
firebaseProjectId=rola-dev
apiBaseUrl=https://us-central1-rola-dev.cloudfunctions.net/api/
releaseTrack=internal
analyticsCollection=false
crashlyticsCollection=false
modelChannel=development
